export const personData = [
  {
    id: 1,
    name: 'Bugs Bunny',
    age: 25,
    gender: 'male',
    hobby: 'reading',
    img: '/public/person_5.jpg.webp',
  },
  {
    id: 2,
    name: 'Tom Cat',
    age: 30,
    gender: 'male',
    hobby: 'swimming',
    img: '/public/person_5.jpg.webp',
  },
  {
    id: 3,
    name: 'Jerry Mouse',
    age: 35,
    gender: 'male',
    hobby: 'hiking',
    img: '/public/person_5.jpg.webp',
  },
  {
    id: 4,
    name: 'Scooby Doo',
    age: 40,
    gender: 'male',
    hobby: 'fishing',
    img: '/public/person_5.jpg.webp',
  },
  {
    id: 5,
    name: 'Daisy Duck',
    age: 45,
    gender: 'female',
    hobby: 'cooking',
    img: '/public/person_5.jpg.webp',
  },
  {
    id: 6,
    name: 'Serbentautas Bordiuras',
    age: 50,
    gender: 'male',
    hobby: 'gardening',
    img: '/public/person_5.jpg.webp',
  },
  {
    id: 7,
    name: 'Jessica Rabbit',
    age: 28,
    gender: 'female',
    hobby: 'painting',
    img: '/public/person_5.jpg.webp',
  },
];
